package com.flowmate.autoxiaoer.agent

/**
 * A single unit of work assigned by [LLMAgent] to [PhoneAgent].
 *
 * LLMAgent decomposes the overall user task into SubTasks and dispatches them
 * one at a time. PhoneAgent executes each SubTask and returns a [SubTaskResult].
 *
 * @property id Sequential identifier for this sub-task (1-based)
 * @property description Natural-language description of what PhoneAgent should do
 * @property preGeneratedTexts Text content already generated by LLMAgent that PhoneAgent
 *   should type verbatim (e.g. a reply message). Key is a human-readable purpose label,
 *   value is the generated text.
 * @property context Optional extra instructions or background information for PhoneAgent
 */
data class SubTask(
    val id: Int,
    val description: String,
    val preGeneratedTexts: Map<String, String> = emptyMap(),
    val context: String = "",
)
